version: '3'
services:
  nginx:
    image: nginx:1.15.8
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3001:80"
    depends_on:
      - app

  app:
    image: nginxdemos/hello:plain-text
    deploy:
      mode: replicated
      replicas: 6
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]  # Check if port 80 responds
      interval: 30s       # Check every 30 seconds
      timeout: 10s        # Timeout after 10 seconds if no response
      retries: 3          # Mark as unhealthy after 3 failed attempts
      start_period: 10s   # Give the container 10 seconds before starting health checks
